### ISSUE TITLE
Well Edit Changes Fail to Commit

### ISSUE THREAD

**Issue by nathanbollig** [nathanbollig/rt-quic-db#85]
Certain Well Edit changes fail to commit to the database. The errors are thrown on the application server and do not display to the user.

### Steps to Reproduce Error
1. Go to View Assay and load an Assay (using John 1 in Team 2)
2. Click a well, right click and go to Well Edit
3. Change a value (I'm seeing this with salt_type but also with other fields)
4. Error is thrown on the server and changes do not commit.

```
127.0.0.1 - - [15/Sep/2021 13:22:20] "GET /submitWellEdits?contents=Sample+X26&salt_type=&salt_conc=1&substrate_type=&substrate_conc=&surfact_type=&surfact_conc=&other_wc_attr=&wc_ID=3957 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\mysql\connector\cursor.py", line 827, in _fetch_warnings
    cur = self._connection.cursor(raw=False)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\mysql\connector\connection.py", line 1186, in cursor
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\sentry_sdk\integrations\flask.py", line 91, in sentry_patched_wsgi_app
    environ, start_response
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\sentry_sdk\integrations\wsgi.py", line 140, in __call__
    reraise(*_capture_exception(hub))
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\sentry_sdk\_compat.py", line 54, in reraise
    raise value
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\sentry_sdk\integrations\wsgi.py", line 136, in __call__
    _sentry_start_response, start_response, transaction
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\sentry_sdk\integrations\flask.py", line 90, in <lambda>
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\flask\app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\main\app_server.py", line 332, in submit_well_edits
    wcModel.save_well_data(data)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\main\model.py", line 369, in save_well_data
    self.wcDao.load_well_updates(file = temp_csv)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\main\db.py", line 776, in load_well_updates
    temp_table, temp_table, temp_table), (path,), multi=True): pass
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\mysql\connector\cursor.py", line 503, in _execute_iter
    self._handle_result(result)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\mysql\connector\cursor.py", line 484, in _handle_result
    self._handle_noresultset(result)
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\mysql\connector\cursor.py", line 451, in _handle_noresultset
    self._handle_warnings()
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\mysql\connector\cursor.py", line 843, in _handle_warnings
    self._warnings = self._fetch_warnings()
  File "C:\Users\natha\Documents\Workstation docs\Data projects\rt-quic-db\venv\lib\site-packages\mysql\connector\cursor.py", line 833, in _fetch_warnings
    "Failed getting warnings; %s" % err)
mysql.connector.errors.InterfaceError: Failed getting warnings; MySQL Connection not available.
```

### Interpretation
The error is occurring in `wcDao.load_well_updates()`, which calls the query `Q_LOAD_WELL_UPDATES`. This is a multi-part query that edits data based on a temp file.

Examination of a temp file corresponding to a failed query:
```
"wc_ID","salt_type","salt_conc","substrate_type","substrate_conc","surfact_type","surfact_conc","other_wc_attr","sample_ID","assay_ID","contents","well_name"
"4124","\N","\N","\N","\N","\N","\N","hi","","942","Sample X1","A01"
```

When the sample is changed to a valid sample, the well edit submission works. Subsequent changes to other fields of that same well also commit. It appears that the empty string submitted from the sample selector may be causing the query to fail. This is "caused" by the change made at Upload Assay level that no longer requires a sample record to be specified, since this is what allows the form to contain an empty value in this field.

**Comment by nathanbollig** [comment]
The code that determines the formatting of the temp file is `ManageWC.save_well_data()`.
This depends on the hierarchical lookup implemented in `get_well_data()`. Note that now that there is no sample at the assay level, the hierarchical lookup should not refer to the assay to find the sample value.
